#! /bin/sh
#
# cpqarrayd    Start/Stop Compaq Array monitor
#
# chkconfig: 345 15 90
# description: The cpqarrayd monitors the status of Compaq Raid Arrays, \
#              and reports via syslog or traps
# processname: cpqarrayd

# Source function library.
. /etc/rc.d/init.d/functions

# Get config.
if [ -f /etc/sysconfig/cpqarrayd ]; then
        . /etc/sysconfig/cpqarrayd
fi

[ -f /usr/sbin/cpqarrayd ] || exit 0

RETVAL=0

# See how we were called.
case "$1" in
  start)
        echo -n "Starting cpqarrayd: "
        daemon /usr/sbin/cpqarrayd $CPQ_PARAMS
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/cpqarrayd
        ;;
  stop)
        echo -n "Stopping cpqarrayd: "
        killproc cpqarrayd
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/cpqarrayd
        ;;
  status)
        status cpqarrayd
        RETVAL=$?
        ;;
  restart|reload)
        $0 stop
        $0 start
        RETVAL=$?
        ;;
  *)
        echo "Usage: cpqarrayd {start|stop|status|restart|reload}"
        exit 1
esac

exit $RETVAL
