#!/bin/sh
#
# chkconfig: 2345 55 55
# description: Monitors smartarray controllers.
#
# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

[ -f @installroot@/sbin/cpqarrayd ] || exit 0


# See how we were called.
case "$1" in
  start)
        # Start daemons.
        echo -n "Starting cpqarrayd: "
        daemon @installroot@/sbin/cpqarrayd
        echo
        touch /var/lock/subsys/cpqarrayd
        ;;
  stop)
        # Stop daemons.
        echo -n "Shutting down cpqarrayd: "
	killproc cpqarrayd
        echo
        rm -f /var/lock/subsys/cpqarrayd
        ;;
  status)
	status cpqarrayd
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
        echo "Usage: cpqarrayd {start|stop|restart|status}"
        exit 1
esac

exit 0
